// minified.js config start -- use this comment to re-create a configuration in the Builder
// - All sections.

/^u/.test(typeof define)&&function(O){var D=this.require=function(r){return O[r]};this.define=function(r,E){O[r]=O[r]||E(D)}}({});
define("minified",function(){function O(a){return a.substr(0,3)}function D(a){return a!=k?""+a:""}function r(a){return"string"==typeof a}function E(a){return!!a&&"object"==typeof a}function N(a){return a&&a.nodeType}function Y(a){return"number"==typeof a}function ea(a){return E(a)&&!!a.getDay}function Da(a){return!0===a||!1===a}function na(a){var b=typeof a;return"object"==b?!(!a||!a.getDay):"string"==b||"number"==b||Da(a)}function x(a){return a}function Ea(a){return a+1}function l(a,b,c){return D(a).replace(b,
c!=k?c:"")}function Fa(a){return l(a,/[\\\[\]\/{}()*+?.$|^-]/g,"\\$&")}function J(a){return l(a,/^\s+|\s+$/g)}function q(a,b,c){for(var d in a)a.hasOwnProperty(d)&&b.call(c||a,d,a[d]);return a}function n(a,b,c){if(a)for(var d=0;d<a.length;d++)b.call(c||a,a[d],d);return a}function K(a,b,c){var d=[],e=m(b)?b:function(a){return b!=a};n(a,function(b,g){e.call(c||a,b,g)&&d.push(b)});return d}function z(a,b,c,d){var e=[];a(b,function(a,g){t(a=c.call(d||b,a,g))?n(a,function(a){e.push(a)}):a!=k&&e.push(a)});
return e}function oa(a,b,c){return z(n,a,b,c)}function hb(a){var b=0;q(a,function(){b++});return b}function Ga(a){var b=[];q(a,function(a){b.push(a)});return b}function B(a,b,c){var d=[];n(a,function(e,f){d.push(b.call(c||a,e,f))});return d}function pa(a,b){if(t(a)){var c=P(b);return Q(R(a,0,c.length),c)}return b!=k&&a.substr(0,b.length)==b}function Ha(a,b){if(t(a)){var c=P(b);return Q(R(a,-c.length),c)||!c.length}return b!=k&&a.substr(a.length-b.length)==b}function Z(a){var b=a.length;return t(a)?
new v(B(a,function(){return a[--b]})):l(a,/[\s\S]/g,function(){return a.charAt(--b)})}function qa(a,b){var c={};n(a,function(a){c[a]=b});return c}function aa(a,b){var c=b||{},d;for(d in a)c[d]=a[d];return c}function fa(a,b){for(var c=b,d=0;d<a.length;d++)c=aa(a[d],c);return c}function Ia(a){return m(a)?a:function(b,c){if(a===b)return c}}function S(a,b,c){return b==k?c:0>b?Math.max(a.length+b,0):Math.min(a.length,b)}function T(a,b,c,d){b=Ia(b);d=S(a,d,a.length);for(var e=S(a,c,0);e<d;e++)if((c=b.call(a,
a[e],e))!=k)return c}function Ja(a,b,c,d){b=Ia(b);d=S(a,d,-1);for(var e=S(a,c,a.length-1);e>d;e--)if((c=b.call(a,a[e],e))!=k)return c}function R(a,b,c){var d=[];if(a)for(c=S(a,c,a.length),b=S(a,b,0);b<c;b++)d.push(a[b]);return d}function U(a){return B(a,x)}function Ka(a){return function(){return new v(V(a,arguments))}}function La(a){var b={};return K(a,function(a){return b[a]?!1:b[a]=1})}function Ma(a,b){var c=qa(b,1);return K(a,function(a){var b=c[a];c[a]=0;return b})}function Na(a,b){for(var c=
0;c<a.length;c++)if(a[c]==b)return!0;return!1}function Q(a,b){var c=m(a)?a():a,d=m(b)?b():b,e;return c==d?!0:c==k||d==k?!1:na(c)||na(d)?ea(c)&&ea(d)&&+c==+d:t(c)?c.length==d.length&&!T(c,function(a,b){if(!Q(a,d[b]))return!0}):!t(d)&&(e=Ga(c)).length==hb(d)&&!T(e,function(a){if(!Q(c[a],d[a]))return!0})}function W(a,b,c){if(m(a))return a.apply(c&&b,B(c||b,x))}function V(a,b,c){return B(a,function(a){return W(a,b,c)})}function Oa(a,b,c,d){return function(){return W(a,b,oa([c,arguments,d],x))}}function ga(a,
b){for(var c=0>b?"-":"",d=(c?-b:b).toFixed(0);d.length<a;)d="0"+d;return c+d}function Pa(a,b,c){var d,e=0,f=c?b:Z(b);a=(c?a:Z(a)).replace(/./g,function(a){return"0"==a?(d=!1,f.charAt(e++)||"0"):"#"==a?(d=!0,f.charAt(e++)||""):d&&!f.charAt(e)?"":a});return c?a:b.substr(0,b.length-e)+Z(a)}function ra(a,b,c){return b!=k&&a?60*parseFloat(a[b]+a[b+1])+parseFloat(a[b]+a[b+2])+c.getTimezoneOffset():0}function Qa(a){return new Date(+a)}function sa(a,b,c){a["set"+b](a["get"+b]()+c);return a}function ha(a,
b,c){return c==k?ha(new Date,a,b):sa(Qa(a),b.charAt(0).toUpperCase()+b.substr(1),c)}function Ra(a,b,c){var d=+b,e=+c,f=e-d;if(0>f)return-Ra(a,c,b);if(b={milliseconds:1,seconds:1E3,minutes:6E4,hours:36E5}[a])return f/b;b=a.charAt(0).toUpperCase()+a.substr(1);a=Math.floor(f/{fullYear:31536E6,month:2628E6,date:864E5}[a]-2);d=sa(new Date(d),b,a);for(f=a;f<1.2*a+4;f++)if(+sa(d,b,1)>e)return f}function ta(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}function Sa(a){return l(a,/[\x00-\x1f'"\u2028\u2029]/g,
ta)}function ba(a,b){for(var c=0,d,e=[];d=b.exec(a);)e.push(a.substring(c,d.index)),c=d.index+d[0].length;e.push(a.substr(c));return e}function ua(a,b){function c(a,c){var d=[];e.call(c||a,a,function(a,b){t(a)?n(a,function(a,c){b.call(a,a,c)}):q(a,function(a,c){b.call(c,a,c)})},b||x,function(){W(d.push,d,arguments)},P);return d.join("")}if(ia[a])return ia[a];var d="with(_.isObject(obj)?obj:{}){"+B(ba(a,/{{|}}}?/g),function(a,b){var c,d=J(a),e=l(d,/^{/),d=d==e?"esc(":"";if(b%2)return(c=/^each\b(\s+([\w_]+(\s*,\s*[\w_]+)?)\s*:)?(.*)/.exec(e))?
"each("+(J(c[4])?c[4]:"this")+", function("+c[2]+"){":(c=/^if\b(.*)/.exec(e))?"if("+c[1]+"){":(c=/^else\b\s*(if\b(.*))?/.exec(e))?"}else "+(c[1]?"if("+c[2]+")":"")+"{":(c=/^\/(if)?/.exec(e))?c[1]?"}\n":"});\n":(c=/^(var\s.*)/.exec(e))?c[1]+";":(c=/^#(.*)/.exec(e))?c[1]:(c=/(.*)::\s*(.*)/.exec(e))?"print("+d+'_.formatValue("'+Sa(c[2])+'",'+(J(c[1])?c[1]:"this")+(d&&")")+"));\n":"print("+d+(J(e)?e:"this")+(d&&")")+");\n";if(a)return'print("'+Sa(a)+'");\n'}).join("")+"}",e=new Function("obj","each",
"esc","print","_",d);99<Ta.push(c)&&delete ia[Ta.shift()];return ia[a]=c}function Ua(a){return l(a,/[<>'"&]/g,function(a){return"&#"+a.charCodeAt(0)+";"})}function va(a,b){return ua(a,Ua)(b)}function M(a){return function(b,c){return new v(a(this,b,c))}}function A(a){return function(b,c,d){return a(this,b,c,d)}}function G(a){return function(b,c,d){return new v(a(b,c,d))}}function m(a){return"function"==typeof a&&!a.item}function t(a){return a&&a.length!=k&&!r(a)&&!N(a)&&!m(a)&&a!==w}function Va(a,
b){for(var c=0;a&&c<a.length;c++)a[c]===b&&a.splice(c--,1)}function ja(a){return parseFloat(l(a,/^[^\d-]+/))}function ka(a){return a.Nia=a.Nia||++Wa}function wa(a,b){var c=[],d={},e;p(a,function(a){p(b(a),function(a){d[e=ka(a)]||(c.push(a),d[e]=!0)})});return c}function Xa(a,b){var c={$position:"absolute",$visibility:"hidden",$display:"block",$height:k},d=a.get(c),c=a.set(c).get("clientHeight");a.set(d);return c*b+"px"}function ib(a,b,c,d,e,f){return function(g,h){var y,F=g||w.event,k=!f,L=h||F.target||
F.srcElement;if(f)for(;L&&L!=b&&!(k=f(L));)L=L.parentNode;k&&(y=(!a.apply(u(f?L:b),c||[F,d])||""==e)&&"|"!=e)&&!h&&(F.preventDefault&&(F.preventDefault(),F.stopPropagation()),F.cancelBubble=!0);return!y}}function xa(a,b){p(b,function(a){a.element.detachEvent("on"+a.b,a.c)})}function Ya(a){X?X.push(a):setTimeout(a,0)}function Za(a,b,c){return H(a,b,c)[0]}function $a(a,b,c){a=u(document.createElement(a));return t(b)||b!=k&&!E(b)?a.add(b):a.set(b).add(c)}function ya(a){return z(p,a,function(a){if(t(a))return ya(a);
N(a)&&(a=a.cloneNode(!0),a.removeAttribute&&a.removeAttribute("id"));return a})}function u(a,b,c){return m(a)?Ya(a):new v(H(a,b,c))}function H(a,b,c){function d(a){a=z(p,a,function L(a){return t(a)?z(p,a,L):a});return g?K(a,function(a){for(;a=a.parentNode;)if(a==g||c)return a==g}):a}function e(a,b){var c=RegExp("(^|\\s+)"+a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var f;if(b&&1!=(b=H(b)).length)return wa(b,function(b){return H(a,b,c)});var g=b&&b[0];if(!r(a))return d(a);if(g&&
1!=N(g))return[];if(1<(b=a.split(/\s*,\s*/)).length)return wa(b,function(a){return H(a,g,c)});if(b=/(\S+)\s+(.+)$/.exec(a))return H(b[2],H(b[1],g),c);if(a!=(b=l(a,/^#/)))return d(document.getElementById(b));var h=(b=/([\w-]*)\.?([\w-]*)/.exec(a))[1];var y=b[2];b=(f=document.getElementsByClassName&&y)?(g||document).getElementsByClassName(y):(g||document).getElementsByTagName(h||"*");if(h=f?h:y)b=K(b,e(h,f?"tagName":"className"));return c?d(b):b}function la(a,b){function c(a,b){var c=RegExp("(^|\\s+)"+
a+"(?=$|\\s)","i");return function(d){return a?c.test(d[b]):!0}}var d={},e=d;if(m(a))return a;if(Y(a))return function(b,c){return c==a};if(!a||"*"==a||r(a)&&(e=/^([\w-]*)\.?([\w-]*)$/.exec(a))){var f=c(e[1],"tagName"),g=c(e[2],"className");return function(a){return 1==N(a)&&f(a)&&g(a)}}if(b)return function(c){return u(a,b).find(c)!=k};u(a).each(function(a){d[ka(a)]=!0});return function(a){return d[ka(a)]}}function ab(a){var b=la(a);return function(a){return b(a)?k:!0}}function p(a,b){t(a)?n(a,b):
a!=k&&b(a,0);return a}function kb(){this.state=null;this.values=[];this.parent=null}function ca(){var a=[],b=arguments,c=b.length,d=0,e=0,f=new kb;f.errHandled=function(){e++;f.parent&&f.parent.errHandled()};var g=f.fire=function(b,c){null==f.state&&null!=b&&(f.state=!!b,f.values=t(c)?c:[c],setTimeout(function(){n(a,function(a){a()})},0));return f};n(b,function F(a,b){try{a.then?a.then(function(a){(E(a)||m(a))&&m(a.then)?F(a,b):(f.values[b]=U(arguments),++d==c&&g(!0,2>c?f.values[b]:f.values))},function(a){f.values[b]=
U(arguments);g(!1,2>c?f.values[b]:[f.values[b][0],f.values,b])}):a(function(){g(!0,U(arguments))},function(){g(!1,U(arguments))})}catch(jb){g(!1,[jb,f.values,b])}});f.stop=function(){n(b,function(a){a.stop&&a.stop()});return f.stop0&&W(f.stop0)};var h=f.then=function(b,c){function d(){try{var a=f.state?b:c;m(a)?function lb(a){try{var b;var c=0;if((E(a)||m(a))&&m(b=a.then)){if(a===g)throw new TypeError;b.call(a,function(a){c++||lb(a)},function(a){c++||g.fire(!1,[a])});g.stop0=a.stop}else g.fire(!0,
[a])}catch(bb){if(!c++&&(g.fire(!1,[bb]),!e))throw bb;}}(W(a,da,f.values)):g.fire(f.state,f.values)}catch(cb){if(g.fire(!1,[cb]),!e)throw cb;}}var g=ca();m(c)&&f.errHandled();g.stop0=f.stop;g.parent=f;null!=f.state?setTimeout(d,0):a.push(d);return g};f.always=function(a){return h(a,a)};f.error=function(a){return h(0,a)};return f}function v(a,b){var c=0;if(a)for(var d=0,e=a.length;d<e;d++){var f=a[d];if(b&&t(f))for(var g=0,h=f.length;g<h;g++)this[c++]=f[g];else this[c++]=f}else this[c++]=b;this.length=
c;this._=!0}function P(){return new v(arguments,!0)}var w=window,za={},Aa={},Wa=1,I={},X=/^[ic]/.test(document.readyState)?k:[],ma={},Ba=0,C=!!document.all&&!document.addEventListener,k=null,da,Ca=ba("January,February,March,April,May,June,July,August,September,October,November,December",/,/g),db=B(Ca,O),eb=ba("Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday",/,/g),mb=B(eb,O),nb=ba("am,pm",/,/g),ob=ba("am,am,am,am,am,am,am,am,am,am,am,am,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm,pm",/,/g),pb={y:["FullYear",
x],Y:["FullYear",function(a){return a%100}],M:["Month",Ea],n:["Month",db],N:["Month",Ca],d:["Date",x],m:["Minutes",x],H:["Hours",x],h:["Hours",function(a){return a%12||12}],k:["Hours",Ea],K:["Hours",function(a){return a%12}],s:["Seconds",x],S:["Milliseconds",x],a:["Hours",ob],w:["Day",mb],W:["Day",eb],z:["TimezoneOffset",function(a,b,c){if(c)return c;b=0>a?-a:a;return(0<a?"-":"+")+ga(2,Math.floor(b/60))+ga(2,b%60)}]},fb={y:0,Y:[0,-2E3],M:[1,1],n:[1,db],N:[1,Ca],d:2,m:4,H:3,h:3,K:[3,1],k:[3,1],s:5,
S:6,a:[3,nb]},ia={},Ta=[];aa({each:A(n),filter:M(K),collect:M(oa),map:M(B),toObject:A(qa),equals:A(Q),sub:M(R),reverse:A(Z),find:A(T),findLast:A(Ja),startsWith:A(pa),endsWith:A(Ha),contains:A(Na),call:M(V),array:A(U),unite:A(Ka),merge:A(fa),uniq:M(La),intersection:M(Ma),join:function(a){return B(this,x).join(a)},reduce:function(a,b){n(this,function(c,d){b=a.call(this,b,c,d)});return b},sort:function(a){return new v(B(this,x).sort(a))},remove:function(){p(this,function(a){C&&1==N(a)&&(p(H("*",a),function(a){xa(0,
I[a.Nia]);delete I[a.Nia]}),xa(0,I[a.Nia]),delete I[a.Nia]);a.parentNode.removeChild(a)})},text:function(){function a(b){var c=N(b);return 1==c?z(p,b.childNodes,a):5>c?b.data:k}return z(p,this,a).join("")},trav:function(a,b,c){var d=Y(b),e=la(d?k:b),f=d?b:c;return new v(wa(this,function(b){for(var c=[];(b=b[a])&&c.length!=f;)e(b)&&c.push(b);return c}))},next:function(a,b){return this.trav("nextSibling",a,b||1)},up:function(a,b){return this.trav("parentNode",a,b||1)},select:function(a,b){return u(a,
this,b)},is:function(a){return!this.find(ab(a))},only:function(a){return new v(K(this,la(a)))},not:function(a){return new v(K(this,ab(a)))},get:function(a,b){var c=this,d=c[0];if(d){if(r(a)){var e=/^(\W*)(.*)/.exec(l(a,/^%/,"@data-")),f=e[1],d=Aa[f]?Aa[f](this,e[2]):"$"==a?c.get("className"):"$$"==a?C?d.style.cssText:c.get("@style"):"$$slide"==a?c.get("$height"):"$$fade"==a||"$$show"==a?"hidden"==c.get("$visibility")||"none"==c.get("$display")?0:"$$fade"==a?C?isNaN(c.get("$filter",!0))?1:c.get("$filter",
!0)/100:isNaN(c.get("$opacity",!0))?1:c.get("$opacity",!0):1:"$$scrollX"==a?w.pageXOffset!=k?w.pageXOffset:(document.documentElement||document.body.parentNode||document.body).scrollLeft:"$$scrollY"==a?w.pageXOffset!=k?w.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop:"$"==f?w.getComputedStyle?w.getComputedStyle(d,k).getPropertyValue(l(e[2],/[A-Z]/g,function(a){return"-"+a.toLowerCase()})):(d.currentStyle||d.style)[l(e[2],/^float$/,"cssFloat")]:"@"==f?d.getAttribute(e[2]):
d[e[2]];return b?ja(d):d}var g={};(t(a)?p:q)(a,function(a){g[a]=c.get(a,b)});return g}},set:function(a,b){var c=this;if(b!==da){var d=/^(\W*)(.*)/.exec(l(l(a,/^\$float$/,"cssFloat"),/^%/,"@data-")),e=d[1];if(za[e])za[e](this,d[2],b);else"$$fade"==a?c.set({$visibility:b?"visible":"hidden"}).set(C?1>b?{$filter:"alpha(opacity = "+100*b+")",$zoom:1}:{$filter:""}:{$opacity:b}):"$$slide"==a?c.set({$visibility:b?"visible":"hidden",$overflow:"hidden",$height:/px/.test(b)?b:function(a,c,d){return Xa(u(d),
b)}}):"$$show"==a?b?c.set({$visibility:b?"visible":"hidden",$display:""}).set({$display:function(a){return"none"==a?"block":a}}):c.set({$display:"none"}):"$$"==a?C?c.set("$cssText",b):c.set("@style",b):p(this,function(c,g){var f=m(b)?b(u(c).get(a),g,c):b;"$"==e?d[2]?c.style[d[2]]=f:p(f&&f.split(/\s+/),function(a){var b=l(a,/^[+-]/),d=c.className||"",e=l(d,RegExp("(^|\\s+)"+b+"(?=$|\\s)"));if(/^\+/.test(a)||b==a&&d==e)e+=" "+b;c.className=J(e)}):"$$scrollX"==a?c.scroll(f,u(c).get("$$scrollY")):"$$scrollY"==
a?c.scroll(u(c).get("$$scrollX"),f):"@"==e?f==k?c.removeAttribute(d[2]):c.setAttribute(d[2],f):c[d[2]]=f})}else r(a)||m(a)?c.set("$",a):q(a,function(a,b){c.set(a,b)});return c},show:function(){return this.set("$$show",1)},hide:function(){return this.set("$$show",0)},add:function(a,b){return this.each(function(c,d){function e(a){t(a)?p(a,e):m(a)?e(a(c,d)):a!=k&&(a=N(a)?a:document.createTextNode(a),f?f.parentNode.insertBefore(a,f.nextSibling):b?b(a,c,c.parentNode):c.appendChild(a),f=a)}var f;e(d&&!m(a)?
ya(a):a)})},fill:function(a){return this.each(function(a){u(a.childNodes).remove()}).add(a)},addAfter:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c.nextSibling)})},addBefore:function(a){return this.add(a,function(a,c,d){d.insertBefore(a,c)})},addFront:function(a){return this.add(a,function(a,c){c.insertBefore(a,c.firstChild)})},replace:function(a){return this.add(a,function(a,c,d){d.replaceChild(a,c)})},clone:M(ya),animate:function(a,b,c){var d=ca(),e=this,f=z(p,this,function(b,
d){var e=u(b),f,g={};q(f=e.get(a),function(c,f){var h=a[c];g[c]=m(h)?h(f,d,b):"$$slide"==c?Xa(e,h):h});return e.dial(f,g,c)}),g=b||500;d.stop0=function(){d.fire(!1);return h()};var h=u.loop(function(a){V(f,[a/g]);a>=g&&(h(),d.fire(!0,[e]))});return d},dial:function(a,b,c){function d(a,b){return/^#/.test(a)?parseInt(6<a.length?a.substr(2*b+1,2):(a=a.charAt(b+1))+a,16):ja(a.split(",")[b])}var e=this,f=c||0,g=m(f)?f:function(a,b,c){return c*(b-a)*(f+(1-f)*c*(3-2*c))+a};return function(c){q(a,function(a,
f){var h=b[a],k=0;e.set(a,0>=c?f:1<=c?h:/^#|rgb\(/.test(h)?"rgb("+Math.round(g(d(f,k),d(h,k++),c))+","+Math.round(g(d(f,k),d(h,k++),c))+","+Math.round(g(d(f,k),d(h,k++),c))+")":l(h,/-?[\d.]+/,D(g(ja(f),ja(h),c))))})}},toggle:function(a,b,c,d){var e=this,f=!1,g,h;return b?(e.set(a),function(y){y!==f&&(h=(f=!0===y||!1===y?y:!f)?b:a,c?(g=e.animate(h,g?g.stop():c,d)).then(function(){g=k}):e.set(h))}):e.toggle(l(a,/\b(?=\w)/g,"-"),l(a,/\b(?=\w)/g,"+"))},values:function(a){var b=a||{};this.each(function(a){var c=
a.name||a.id,e=D(a.value);if(/form/i.test(a.tagName))for(c=0;c<a.elements.length;c++)u(a.elements[c]).values(b);else!c||/ox|io/i.test(a.type)&&!a.checked||(b[c]=b[c]==k?e:z(p,[b[c],e],x))});return b},offset:function(){for(var a=this[0],b={x:0,y:0};a;)b.x+=a.offsetLeft,b.y+=a.offsetTop,a=a.offsetParent;return b},on:function(a,b,c,d,e){return m(b)?this.on(k,a,b,c,e):r(d)?this.on(a,b,c,k,d):this.each(function(f,g){p(a?H(a,f):f,function(a){p(D(b).split(/\s/),function(b){var f=l(b,/[?|]/),h=!!e&&("blur"==
f||"focus"==f),k=ib(c,a,d,g,l(b,/[^?|]/g),e&&la(e,a));b={element:a,c:k,b:f,capture:h};(c.M=c.M||[]).push(b);C?(a.attachEvent("on"+b.b+(h?"in":""),k),f=ka(a),(I[f]=I[f]||[]).push(b)):(a.addEventListener(f,k,h),(a.M=a.M||[]).push(b))})})})},onOver:function(a,b){var c=this,d=[];return m(b)?this.on(a,"|mouseover |mouseout",function(a,f){var e=a.relatedTarget||a.toElement,h="mouseout"!=a.type;d[f]===h||!h&&e&&(e==c[f]||u(e).up(c[f]).length)||(d[f]=h,b.call(this,h,a))}):this.onOver(k,a)},onFocus:function(a,
b,c){return m(b)?this.on(a,"|blur",b,[!1],c).on(a,"|focus",b,[!0],c):this.onFocus(k,a,b)},onChange:function(a,b,c){return m(b)?this.on(a,C?"|propertychange |change |keyup |clicked":"|input |change |clicked",function(a,c){var d=this[0];var e=C&&/select/i.test(d.tagName)?d.options[d.selectedIndex].text:/ox|io/i.test(d.type)?d.checked:d.value;e!=d.NiaP&&b.call(this,d.NiaP=e,c)},c):this.onChange(k,a,b)},onClick:function(a,b,c,d){return m(b)?this.on(a,"click",b,c,d):this.onClick(k,a,b,c)},trigger:function(a,
b){return this.each(function(c){for(var d,e=c;e&&!d;)p(C?I[e.Nia]:e.M,function(e){e.b==a&&(d=d||!e.c(b,c))}),e=e.parentNode})},per:function(a,b){if(m(a))for(var c=this.length,d=0;d<c;d++)a.call(this,new v(k,this[d]),d);else u(a,this).per(b);return this},ht:function(a,b){var c=2<arguments.length?fa(R(arguments,1)):b;return this.set("innerHTML",m(a)?a(c):/{{/.test(a)?va(a,c):/^#\S+$/.test(a)?va(Za(a).text,c):a)}},v.prototype);aa({request:function(a,b,c,d){d=d||{};var e,f=0,g=ca(),h=c&&c.constructor==
d.constructor;try{g.xhr=e=w.XMLHttpRequest?new XMLHttpRequest:new ActiveXObject("Msxml2.XMLHTTP.3.0"),g.stop0=function(){e.abort()},h&&(c=z(q,c,function(a,b){return z(p,b,function(b){return encodeURIComponent(a)+(b!=k?"="+encodeURIComponent(b):"")})}).join("&")),c==k||/post/i.test(a)||(b+="?"+c,c=k),e.open(a,b,!0,d.user,d.pass),h&&/post/i.test(a)&&e.setRequestHeader("Content-Type","application/x-www-form-urlencoded"),q(d.headers,function(a,b){e.setRequestHeader(a,b)}),q(d.xhr,function(a,b){e[a]=b}),
e.onreadystatechange=function(){4!=e.readyState||f++||(200<=e.status&&300>e.status?g.fire(!0,[e.responseText,e]):g.fire(!1,[e.status,e.responseText,e]))},e.send(c)}catch(y){f||g.fire(!1,[0,k,D(y)])}return g},toJSON:function b(c){return c==k?""+c:r(c=c.valueOf())?'"'+l(c,/[\\\"\x00-\x1f\u2028\u2029]/g,ta)+'"':t(c)?"["+z(p,c,b).join()+"]":E(c)?"{"+z(q,c,function(c,e){return b(c)+":"+b(e)}).join()+"}":D(c)},parseJSON:w.JSON?w.JSON.parse:function(b){b=l(b,/[\x00\xad\u0600-\uffff]/g,ta);if(/^[[\],:{}\s]*$/.test(l(l(b,
/\\["\\\/bfnrtu]/g),/"[^"\\\n\r]*"|true|false|null|[\d.eE+-]+/g)))return eval("("+b+")")},ready:Ya,loop:function(b){function c(b){q(ma,function(c,d){d(b)});Ba&&h(c)}function d(){ma[g]&&(delete ma[g],Ba--);return f}var e,f=0,g=Wa++,h=w.requestAnimationFrame||function(b){setTimeout(function(){b(+new Date)},33)};ma[g]=function(c){e=e||c;b(f=c-e,d)};Ba++||h(c);return d},off:function(b){p(b.M,function(b){C?(b.element.detachEvent("on"+b.b+(b.capture?"in":""),b.c),Va(I[b.element.Nia],b)):(b.element.removeEventListener(b.b,
b.c,b.capture),Va(b.element.M,b))});b.M=k},setCookie:function(b,c,d,e){document.cookie=b+"="+(e?c:escape(c))+(d?"; expires="+(E(d)?d:new Date(+new Date+864E5*d)).toUTCString():"")},getCookie:function(b,c){var d,e=(d=(new RegExp("(^|;)\\s*"+b+"=([^;]*)")).exec(document.cookie))&&d[2];return c?e:e&&unescape(e)},wait:function(b,c){var d=ca(),e=setTimeout(function(){d.fire(!0,c)},b);d.stop0=function(){d.fire(!1);clearTimeout(e)};return d}},u);aa({filter:G(K),collect:G(oa),map:G(B),sub:G(R),reverse:Z,
each:n,toObject:qa,find:T,findLast:Ja,contains:Na,startsWith:pa,endsWith:Ha,equals:Q,call:G(V),array:U,unite:Ka,merge:fa,uniq:G(La),intersection:G(Ma),keys:G(Ga),values:G(function(b,c){var d=[];c?n(c,function(c){d.push(b[c])}):q(b,function(b,c){d.push(c)});return d}),copyObj:aa,extend:function(b){return fa(R(arguments,1),b)},range:function(b,c){for(var d=[],e=c==k?b:c,f=c!=k?b:0;f<e;f++)d.push(f);return new v(d)},bind:Oa,partial:function(b,c,d){return Oa(b,this,c,d)},eachObj:q,mapObj:function(b,c,
d){var e={};q(b,function(f,g){e[f]=c.call(d||b,f,g)});return e},filterObj:function(b,c,d){var e={};q(b,function(f,g){c.call(d||b,f,g)&&(e[f]=g)});return e},isList:t,isFunction:m,isObject:E,isNumber:Y,isBool:Da,isDate:ea,isValue:na,isString:r,toString:D,dateClone:Qa,dateAdd:ha,dateDiff:Ra,dateMidnight:function(b){b=b||new Date;return new Date(b.getFullYear(),b.getMonth(),b.getDate())},pad:ga,formatValue:function(b,c){var d=l(b,/^\?/);if(ea(c)){var e;if(e=/^\[(([+-])(\d\d)(\d\d))\]\s*(.*)/.exec(d)){var f=
e[1];c=ha(c,"minutes",ra(e,2,c));d=e[5]}return l(d,/(\w)(\1*)(?:\[([^\]]+)\])?/g,function(b,d,e,l){if(d=pb[d])b=c["get"+d[0]](),l=l&&l.split(","),b=t(d[1])?(l||d[1])[b]:d[1](b,l,f),b==k||r(b)||(b=ga(e.length+1,b));return b})}return T(d.split(/\s*\|\s*/),function(b){var d;if(d=/^([<>]?)(=?)([^:]*?)\s*:\s*(.*)$/.exec(b)){b=c;var e=+d[3];if(isNaN(e)||!Y(b))b=b==k?"null":D(b),e=d[3];if(d[1]){if(!d[2]&&b==e||"<"==d[1]&&b>e||">"==d[1]&&b<e)return k}else if(b!=e)return k;d=d[4]}else d=b;return Y(c)?d.replace(/[0#](.*[0#])?/,
function(b){var d=/^([^.]+)(\.)([^.]+)$/.exec(b)||/^([^,]+)(,)([^,]+)$/.exec(b),e=0>c?"-":"",f=/(\d+)(\.(\d+))?/.exec((e?-c:c).toFixed(d?d[3].length:0));b=d?d[1]:b;var g=d?Pa(d[3],l(f[3],/0+$/),!0):"";return(e?"-":"")+("#"==b?f[1]:Pa(b,f[1]))+(g.length?d[2]:"")+g}):d})},parseDate:function(b,c){var d={},e=1,f,g,h=l(b,/^\?/);if(h!=b&&!J(c))return k;if(g=/^\[([+-])(\d\d)(\d\d)\]\s*(.*)/.exec(h)){var m=g;h=g[4]}if(!(g=(new RegExp(h.replace(/(.)(\1*)(?:\[([^\]]*)\])?/g,function(b,c,g,h){return/[dmhkyhs]/i.test(c)?
(d[e++]=c,b=g.length+1,"(\\d"+(2>b?"+":"{1,"+b+"}")+")"):"z"==c?(f=e,e+=3,"([+-])(\\d\\d)(\\d\\d)"):/[Nna]/.test(c)?(d[e++]=[c,h&&h.split(",")],"([a-zA-Z\\u0080-\\u1fff]+)"):/w/i.test(c)?"[a-zA-Z\\u0080-\\u1fff]+":/\s/.test(c)?"\\s+":Fa(b)}))).exec(c)))return da;for(var h=[0,0,0,0,0,0,0],p=1;p<e;p++){var u=g[p],q=d[p];if(t(q)){var r=q[0];var n=fb[r];var v=n[0];n=T(q[1]||n[1],function(b,c){if(pa(u.toLowerCase(),b.toLowerCase()))return c});if(n==k)return da;h[v]="a"==r?h[v]+12*n:n}else q&&(r=parseFloat(u),
n=fb[q],t(n)?h[n[0]]+=r-n[1]:h[n]+=r)}h=new Date(h[0],h[1],h[2],h[3],h[4],h[5],h[6]);return ha(h,"minutes",-ra(m,1,h)-ra(g,f,h))},parseNumber:function(b,c){var d=l(b,/^\?/);if(d!=b&&!J(c))return k;d=/(^|[^0#.,])(,|[0#.]*,[0#]+|[0#]+\.[0#]+\.[0#.,]*)($|[^0#.,])/.test(d)?",":".";d=parseFloat(l(l(l(c,","==d?/\./g:/,/g),d,"."),/^[^\d-]*(-?\d)/,"$1"));return isNaN(d)?da:d},trim:J,isEmpty:function(b,c){return b==k||!b.length||c&&/^\s*$/.test(b)},escapeRegExp:Fa,escapeHtml:Ua,format:function(b,c,d){return ua(b,
d)(c)},template:ua,formatHtml:va,promise:ca},P);if(C){var gb=function(){V(X);X=k};document.attachEvent("onreadystatechange",function(){/^[ic]/.test(document.readyState)&&gb()});w.attachEvent("onload",gb)}else document.addEventListener("DOMContentLoaded",function(){V(X);X=k},!1);w.f=function(){p(I,xa)};return{HTML:function(){var b=$a("div");return P(W(b.ht,b,arguments)[0].childNodes)},_:P,$:u,$$:Za,EE:$a,M:v,getter:Aa,setter:za}});